# Generated by Django 5.2.13 on 2026-04-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AtualizacaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='api.posto')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocombustivel')),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='api.atualizacaopreco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_dadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('atualizacao', 'usuario')},
            },
        ),
    ]
