# Generated by Django 5.2.13 on 2026-04-09 18:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atualizacaopreco',
            options={'verbose_name': 'Atualização de Preço', 'verbose_name_plural': 'Atualizações de Preços'},
        ),
        migrations.AlterModelOptions(
            name='posto',
            options={'verbose_name': 'Posto', 'verbose_name_plural': 'Postos'},
        ),
        migrations.AlterModelOptions(
            name='reacao',
            options={'verbose_name': 'Reação', 'verbose_name_plural': 'Reações'},
        ),
        migrations.AlterModelOptions(
            name='tipocombustivel',
            options={'verbose_name': 'Tipo de Combustível', 'verbose_name_plural': 'Tipos de Combustíveis'},
        ),
        migrations.AlterField(
            model_name='posto',
            name='localizacao',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
