# Generated by Django 5.2.13 on 2026-05-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='bandeira',
            field=models.CharField(default='Bandeira Branca', max_length=50),
        ),
        migrations.AddField(
            model_name='posto',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
