# Generated by Django 5.2.13 on 2026-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
