# Generated by Django 5.2.13 on 2026-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posto_bandeira_posto_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='avaliacao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
