# Generated by Django 5.2.13 on 2026-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_atualizacaopreco_options_alter_posto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocombustivel',
            name='cor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
