# Generated by Django 5.2.16 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_station_user_ratings_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
