# Generated by Django 5.2.13 on 2026-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_posto_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocombustivel',
            options={'ordering': ['order', 'nome'], 'verbose_name': 'Tipo de Combustível', 'verbose_name_plural': 'Tipos de Combustíveis'},
        ),
        migrations.AddField(
            model_name='tipocombustivel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
