# Generated by Django 5.2.16 on 2026-08-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_station_created_at_station_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
