# Generated by Django 5.2.16 on 2026-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes_received_test',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
