limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=5r/s;

# Block for HTTP
server {
    listen 80;
    server_name vaiabastecendo.lucsdsm.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Block for HTTPS
server {
    listen 8443 ssl;
    server_name vaiabastecendo.lucsdsm.com.br;

    ssl_certificate /etc/letsencrypt/live/vaiabastecendo.lucsdsm.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vaiabastecendo.lucsdsm.com.br/privkey.pem;

    limit_req zone=ratelimit burst=10 nodelay;

    location ~* (/\.env|/\.git|/config\.json|/backup|wp-|xmlrpc\.php|\.php) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}